### ISSUE TITLE
[M]タイヤって車重で凹むんですね……

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#106]
- [x] タイヤの凹み量を保存する変数を追加(Rdep)(タイヤの凹み量半径)
- [x] それに伴うパラメータ入力画面修正
- [x] CSV修正(読み飛ばし行は21に)
- [x] calculate関数修正(タイヤ半径からDdepを引く処理)

- [x] パラメータ入力画面スクリーンショット取り直し
- [x] グラフ描画画面スクリーンショット取り直し
- [x] 再計算したCSVをExcelに貼り付け

**Comment by kapipara** [comment]
fix/#103_fix で修正中． 402f0a3 で変数追加，読み飛ばし行数変更，calculate関数修正を行いました．

**Comment by kapipara** [comment]
疲れからかチケット番号を103に空目してブランチ名も間違ってますごめんなさい……

**Comment by kapipara** [comment]
@sun-yryr 単位は[cm]なのでお気をつけください

**Comment by sun-yryr** [comment]
多分直ってると思います
実機確認は明日朝行ってからで，，，

**Comment by sun-yryr** [comment]
確認できました
