### ISSUE TITLE
グラフの軸がヤバい！！！

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#107]
右縦軸がkmf･mになってるけど，正しくはkgf･mです．
・は半角カナの方でお願いします．
@sun-yryr 

![グラフ画面(縦)(自動生成)](https://user-images.githubusercontent.com/27667873/66327700-395f6580-e966-11e9-894d-10326566ea46.png)

**Comment by sun-yryr** [comment]
https://github.com/yamalab-team/toragi_bikePower/commit/b2b431d5da0d01bfc86e93944c67d7b5c013f47d で直ったはずです
