### ISSUE TITLE
グラフ描画関係

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#27]
グラフの下は塗らないで，横軸rpmの1つのグラフにまとめたいそうです。

**Comment by sun-yryr** [comment]
![スクリーンショット 2019-06-29 14 59 04](https://user-images.githubusercontent.com/29156490/60380303-83d76900-9a7e-11e9-821d-177ac2cd67e3.png)
いいんでね？

**Comment by sun-yryr** [comment]
透過度を上げる
### PSのせいでトルクが見えないので

**Comment by sun-yryr** [comment]
データ選択するとき，初期値は最新データにしますか

**Comment by sun-yryr** [comment]
透過度......無理！www
