### ISSUE TITLE
ボタン連打対応

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#39]
STATEで判断すればいけそう？

**Comment by sun-yryr** [comment]
webだけど，
- UserDataが未登録だったら情報登録ボタンのみ表示
- STANDBYなら情報登録ボタン，STARTボタン，結果表示ボタン表示
- RUNNINGならSTOPボタンのみ表示
でやろうかなと。（結果表示ボタンは過去のを観れるようにした前提）

**Comment by kapipara** [comment]
お，いいっすね
UserDataがないときは，ボタン部分をhtmlから剥ぎ取っちゃう感じだろうか

ページ読み込みが終わる前に連打されたらどうなるんだろう

**Comment by sun-yryr** [comment]
うーん結局arduino側で弾いてもらう必要があるか......

**Comment by kapipara** [comment]
ん，これ物理ボタン側はvoid loop内でstatusを参照してるから連打対応だと思う

**Comment by sun-yryr** [comment]
それなら閉じていいかもしれない
