### ISSUE TITLE
data too littleで死ぬやつ

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#60]
計算時にdata too littleで死ぬと再起動して/result行って死んじゃうやつ，どうにかなったりしますか……？ @sun-yryr

**Comment by sun-yryr** [comment]
data too littleは修正済み #59 

## 多分エラー吐くところ
- /result 直アクセス
    → argないから実行時エラーかな？
- /result パラメータあり
    → calculateの元データのcountLine？で再起動
- 上記で再起動した場合、ストリームを止められてないので再びcalculateで落ちる(無限)
- 1085以降のcatchError(NO_FILE)が回収しきれてないことが今わかりました……（これはどのフローでも当たらないかも？）

**Comment by kapipara** [comment]
ごめんなさい，これまーじしてないのが原因でした…
