### ISSUE TITLE
ボタンで計測したときにStopが出てから再起動せずにメニュー表示

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#77]
1秒後にメニューに戻す

**Comment by sun-yryr** [comment]
これ直ってませんか？

**Comment by kapipara** [comment]
えーマジですか確認します

**Comment by kapipara** [comment]
ボタン操作のときは計測終了時に再起動させるヤクザ仕様にしたのか，らじゃーです

**Comment by sun-yryr** [comment]
https://github.com/yamalab-team/toragi_bikePower/commit/aab860b3f426189c969496b4aa4f8199f4c6900b 良さそうじゃない？

**Comment by kapipara** [comment]
なるほど
Webで計測終了時にメニュー出ないガバしてたな
ありがとうございます
