### ISSUE TITLE
グラフ描画修正

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#78]
・軸の文字を大きくする
・凡例がおかしい

**Comment by sun-yryr** [comment]
しました
とりあえずfontSize25です

**Comment by sun-yryr** [comment]
## 直せるか不明点
- [ ] 横軸の設定(x1000 かつ 値を 2桁にする)
- [ ] 左右の横軸の方眼がずれている件
- [ ] 右側の軸ラベルの読み方向が逆(下から上)

## 直せる
- [ ] 最高回転数から最高速度を表示するやつ

**Comment by sun-yryr** [comment]
> 左右の横軸の方眼がずれている件

試しに canvasjsに変えて実装してみた。確認する

**Comment by sun-yryr** [comment]
右側の軸ラベル，無理です
これならいける
![スクリーンショット 2019-09-28 16 28 41](https://user-images.githubusercontent.com/29156490/65813223-25e92780-e20d-11e9-9850-417001100c34.png)

**Comment by kapipara** [comment]
えー，これは説得しました．
右側ラベル，現状で良いそうです． @sun-yryr

**Comment by kapipara** [comment]
代わりに #95 がヤバいです

**Comment by sun-yryr** [comment]
ありがとうございまs

**Comment by sun-yryr** [comment]
縦軸がずれる件。
ユーザーに目盛分割数を決めてもらって，こちらで計算して出す

## 追加するもの
- html -> 目盛分割数
- js -> stepSizeの計算と適用

**Comment by sun-yryr** [comment]
#101 で修正しました

**Comment by sun-yryr** [comment]
ラベルの向きできちゃったの笑う
#104
