### ISSUE TITLE
calculate関数の修正

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#9]
mvAveSumとmvValArrayがグローバルで定義されてるので，再定義エラー吐きそう。
ギア比の計算を構造体から受け取るので，そのうちyryrからまーじ。
コンパイルは通ったけど，正常な結果が出るかは不明。

明日はその辺から作業。

**Comment by kapipara** [comment]
トータルギア比の計算以外は修正

**Comment by sun-yryr** [comment]
SDに出力されるファイルの中で，PSにおかしな値があったので確認をお願いします
スクショとかはslackに送ります
