### ISSUE TITLE
[M] あうあうあー

### ISSUE THREAD

**Issue by kapipara** [yamalab-team/toragi_bikePower#95]
- rpm範囲±1000くらい多めに(9250だったら9500まで、9250-9750なら10000まで、とか？)
- 凡例を上かグラフ内に
- RTKの走行抵抗加味
- パワー範囲も変えたい(パワーだけで良い)(パワー変えたらトルクも合わせて変わるから)

**Comment by sun-yryr** [comment]
凡例ok

**Comment by kapipara** [comment]
RTK OK

**Comment by sun-yryr** [comment]
> パワー変えたらトルクも変わるから

よくわからなかったから両縦軸変更できるようになってるけど，これでいいのかな感がある

**Comment by kapipara** [comment]
らじゃーです
RTKのExcel修正したら聞きに行ってみる
